"""add veg field

Revision ID: 68df49888e42
Revises: 27e93e9f6f9e
Create Date: 2021-04-25 00:26:03.611223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68df49888e42'
down_revision = '27e93e9f6f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('veg', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('veg')

    # ### end Alembic commands ###
